export const multiLang = {
  en: {
    headerText: 'Rail',
    PNR_Question: 'Great to meet you. Kindly provide PNR number to proceed',
    submitButton: 'submit',
    introQuestion: 'PNR verified successfully. What brings you here today?',
    introQuestionBox: 'Hello Nishant, What brings you here today?',
    selectionRequired: 'Please select an option below:',
    categoriesArray: [
      'Passenger Services',
      'Ticketing and Reservation',
      'Security and Safety',
      'General Information'
    ],
    queryIntroMessage: 'Please enter your query...',
    placeholderText: 'Enter your message...',
    botThinkingText: 'Thinking...',
    youHaveSelected: 'You have selected',
    imageUploadQuestion:
      'if you want to upload an image you can before typing the messsage',
    selectedContinuation: '. How can I assist you with this?',
    imageUploadQuestion:
      'if you want to upload an image you can before typing the messsage',
    NavbarTitle: 'RailMadad',
    NavbarSubTitle: 'For Inquiry, Assistance & Grievance Redressal',
    NavbarSubTitle2: 'for Security/ Medical Assistance',
    NavbarFAQ: 'FAQ',
    NavbarSearch: 'Search',
    EightButton_1: 'Ticket Booking',
    EightButton_2: 'Train Enquiry',
    EightButton_3: 'Reservation Enquiry',
    EightButton_4: 'Retiring Room Booking',
    EightButton_5: 'Indian Railways',
    EightButton_6: 'UTS Ticketing',
    EightButton_7: 'Freight Business ',
    EightButton_8: 'Railway Parcel Website',
    seachTicket: 'Search Ticket',
    askUUID: 'Enter UUID',
    compdetails: 'Complaint Details',
    PNR: 'PNR:',
    UUID: 'UUID:',
    CreatedAt: 'Created at:',
    Status: 'Status:',
    Department: 'Department:',
    Subtype: 'Subtype:',
    AISummary: 'AI Summary:',
    OriginalQ: 'Original Query:',
    Severity: 'Severity:'
  },

  hi: {
    headerText: 'रेल',
    PNR_Question:
      'बड़ा अच्छा लगा आपसे मिल के। कृपया आगे बढ़ने के लिए पीएनआर नंबर प्रदान करें',
    submitButton: 'प्रस्तुत',
    introQuestion:
      'पीएनआर सफलतापूर्वक सत्यापित हो गया है। आज आपको यहाँ क्यों लाया है?',
    introQuestionBox: 'नमस्ते ओम, आज आपको यहाँ क्यों लाया है?',
    selectionRequired: 'कृपया नीचे दिए गए विकल्प में से चुनें:',
    categoriesArray: [
      'यात्री सेवाएं',
      'टिकट और आरक्षण',
      'सुरक्षा और सुरक्षा',
      'सामान्य जानकारी'
    ],
    queryIntroMessage: 'कृपया अपना प्रश्न दर्ज करें...',
    placeholderText: 'अपना संदेश दर्ज करें...',
    botThinkingText: 'सोच रहा है...',
    youHaveSelected: 'आपने चयन किया है',
    imageUploadQuestion:
      'यदि आप एक छवि अपलोड करना चाहते हैं तो आप संदेश लिखने से पहले कर सकते हैं',
    selectedContinuation: '। मैं इसमें आपकी कैसे सहायता कर सकता हूँ?',
    imageUploadQuestion:
      'यदि आप एक छवि अपलोड करना चाहते हैं तो आप संदेश लिखने से पहले कर सकते हैं',
    NavbarTitle: 'रेलमदद',
    NavbarSubTitle: 'पूछताछ, सहायता और शिकायतों का समाधान',
    NavbarSubTitle2: 'सुरक्षा/ चिकित्सा सहायता के लिए',
    NavbarFAQ: 'सामान्य प्रश्न',
    NavbarSearch: 'खोज',
    EightButton_1: 'टिकट बुकिंग',
    EightButton_2: 'ट्रेन जांच',
    EightButton_3: 'रिजर्वेशन जांच',
    EightButton_4: 'रिटायरिंग रूम बुकिंग',
    EightButton_5: 'भारतीय रेलवे',
    EightButton_6: 'यूटीएस टिकटिंग',
    EightButton_7: 'फ्रेट व्यापार',
    EightButton_8: 'रेलवे पार्सल वेबसाइट',
    seachTicket: 'टिकट खोजें',
    askUUID: 'UUID दर्ज करें',
    compdetails: 'शिकायत विवरण',
    PNR: 'PNR:',
    UUID: 'UUID:',
    CreatedAt: 'बनाया गया:',
    Status: 'स्थिति:',
    Department: 'विभाग:',
    Subtype: 'उप प्रकार:',
    AISummary: 'एआई सारांश:',
    OriginalQ: 'मूल प्रश्न:',
    Severity: 'तीव्रता:'
  },
  tm: {
    headerText: 'ரயில்',
    PNR_Question:
      'உங்களை சந்தித்ததற்கு மிக்க மகிழ்ச்சி. தயவுசெய்து பிஎன்ஆர் எண்ணை வழங்கவும்',
    submitButton: 'சமர்ப்பிக்கவும்',
    introQuestion:
      'பிஎன்ஆர் வெற்றிகரமாக சரிபார்க்கப்பட்டுள்ளது. உங்களை இன்று இங்கே என்ன கொண்டு வ இருக்கிறீர்கள்?',
    introQuestionBox: 'வணக்கம் ஓம், உங்களை இங்கே என்ன கொண்டு வ இருக்கிறீர்கள்?',
    selectionRequired: 'தயவுசெய்து கீழே உள்ள ஒன்றை தேர்ந்தெடுக்கவும்:',
    categoriesArray: [
      'பயணிகள் சேவைகள்',
      'டிக்கெட் மற்றும் ஆரக்கச்சன்',
      'பாதுகாப்பு மற்றும் பாதுகாப்பு',
      'பொது தகவல்'
    ],
    queryIntroMessage: 'உங்கள் கேள்வியை உள்ளிடவும்',
    placeholderText: 'உங்கள் செய்தியை உள்ளிடவும்...',
    botThinkingText: 'சிந்திக்கிறது...',
    youHaveSelected: 'நீங்கள் தேர்ந்தெடுத்துள்ளீர்கள்',
    imageUploadQuestion:
      'செய்தியை டைப் செய்யும் முன்பு ஒரு படத்தை அப்லோட் செய்ய விரும்பினால்',
    selectedContinuation: '. இதுவரை நான் உங்களுக்கு எப்படி உதவ முடியும்?',
    imageUploadQuestion:
      'செய்தியை டைப் செய்யும் முன்பு ஒரு படத்தை அப்லோட் செய்ய விரும்பினால்',
    NavbarTitle: 'ரெயில்மதத்',
    NavbarSubTitle: 'கேள்வி, உதவி மற்றும் புகார் திருத்தம்',
    NavbarSubTitle2: 'பாதுகாப்பு/ மருத்துவ உதவி',
    NavbarFAQ: 'கேள்விகள்',
    NavbarSearch: 'தேடு',
    EightButton_1: 'டிக்கெட் பூக்கிங்',
    EightButton_2: 'ரயில் கேள்வி',
    EightButton_3: 'ரிசர்வேஷன் கேள்வி',
    EightButton_4: 'ரிடயரிங் ரூம் பூக்கிங்',
    EightButton_5: 'இந்திய ரயில்வேஸ்',
    EightButton_6: 'யூடிஎஸ் டிக்கெட்டிங்',
    EightButton_7: 'ஃப்ரெய்ட் பிஸ்னஸ்',
    EightButton_8: 'ரெயில்வே பார்சல் வலைத்தளம்',
    seachTicket: 'டிக்கெட் தேடு',
    askUUID: 'UUID உள்ளிடவும்',
    compdetails: 'புகார் விவரங்கள்',
    PNR: 'PNR:',
    UUID: 'UUID:',
    CreatedAt: 'உருவாக்கப்பட்டது:',
    Status: 'நிலை:',
    Department: 'துறை:',
    Subtype: 'உப வகை:',
    AISummary: 'ஏஆய் சுருக்கம்:',
    OriginalQ: 'மூல கேள்வி:',
    Severity: 'கஷ்டகாலம்:'
  }
};

const options = [
  'Luggage/Parcels',
  'Goods',
  'Medical Assistance',
  'Facilities For women With special needs',
  'Divyangjan Facilities',
  'Passenger Amenities',
  'Cleanliness',
  'Water Availability',
  'Catering and Vending Service',
  'Miscellaneous',
  'Staff Behaviour',
  'Electrical Equipment',
  'Reserved Tickets',
  'Unreserved Tickets',
  'Refund of Tickets',
  'Overcrowding in Coaches',
  'Sexual Harassment/Misbehaviour',
  'Chain Pulling',
  'Nuisance by Unauthorized Persons',
  'Harassment/Extortion by Authorities',
  'Suspicious or Unclaimed Items',
  'Missing or Unresponsive Passenger',
  'Substance Abuse',
  'Violence/Disorder',
  'Passenger Accident',
  'Lost/Found',
  'Other Issues'
];

export const availableDepartments = {
  'Passenger Services': options,
  'Ticketing and Reservation': options,
  'Security and Safety': options,
  'General Information': options,
  'यात्री सेवाएं': options,
  'टिकट और आरक्षण': options,
  'सुरक्षा और सुरक्षा': options,
  'जनरल जानकारी': options,
  'பயணிகள் சேவைகள்': options,
  'டிக்கெட் மற்றும் ஆரக்கச்சன்': options,
  'பாதுகாப்பு மற்றும் பாதுகாப்பு': options,
  'பொது தகவல்': options
};
